# Copyright 2026 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Create toy prompt parquet files for Mode (2a) agentic GRPO smoke tests.

Online agentic RL does **not** load offline nested-turn trajectories for
training. The parquet only seeds the initial user request; the multi-turn
reason → rewrite → tool → reflect loop is generated by
``DiffusionARMultiTurnAgentLoop`` at rollout time.

Schema mirrors the FlowGRPO dummy data used by jpeg_compressibility e2e
smokes so acceptance can run without an external reward model:

  data_source / prompt / ability / reward_model / extra_info

Default output paths match ``run_lance_agentic_grpo.sh``:
  ~/data/agentic/train.parquet
  ~/data/agentic/val.parquet
"""

from __future__ import annotations

import argparse
import os

import pandas as pd

DATA_SOURCE = "jpeg_compressibility"
ABILITY = "agentic_prompt_rewrite"

# Attribute-heavy requests that invite multi-turn reflection / rewriting.
USER_PROMPTS = [
    "Generate an image of a cat wearing a blue hat",
    "Create a sunset over snowy mountains with a red cabin",
    "Draw a silver robot painting a colorful landscape on an easel",
    "A glass of orange juice next to three green apples on a wooden table",
    "A yellow bicycle leaning against a blue brick wall in soft morning light",
    "A small brown dog wearing red sunglasses sitting on a white sofa",
    "An astronaut holding a purple umbrella on the surface of Mars",
    "A vintage typewriter with the word HELLO typed in bold letters",
]


def build_rows(split: str, n: int) -> list[dict]:
    """Build ``n`` RLHFDataset-compatible rows for the given split."""
    rows = []
    for i in range(n):
        prompt_text = USER_PROMPTS[i % len(USER_PROMPTS)]
        rows.append(
            {
                "data_source": DATA_SOURCE,
                "prompt": [
                    {"role": "user", "content": prompt_text},
                ],
                "ability": ABILITY,
                "reward_model": {"style": "rule", "ground_truth": prompt_text},
                "extra_info": {
                    "split": split,
                    "index": i,
                    "raw_prompt": prompt_text,
                    "toy_agentic": True,
                },
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate toy agentic GRPO parquet seeds for PR1 acceptance smoke"
    )
    parser.add_argument(
        "--local_save_dir",
        default=os.path.expanduser("~/data/agentic"),
        help="Directory to write train.parquet and val.parquet",
    )
    parser.add_argument("--train_size", type=int, default=8, help="Number of training samples")
    parser.add_argument("--val_size", type=int, default=4, help="Number of validation samples")
    args = parser.parse_args()

    os.makedirs(args.local_save_dir, exist_ok=True)

    train_df = pd.DataFrame(build_rows("train", args.train_size))
    val_df = pd.DataFrame(build_rows("val", args.val_size))

    train_path = os.path.join(args.local_save_dir, "train.parquet")
    val_path = os.path.join(args.local_save_dir, "val.parquet")

    train_df.to_parquet(train_path)
    val_df.to_parquet(val_path)

    print(f"Wrote {len(train_df)} train samples to {train_path}")
    print(f"Wrote {len(val_df)} val samples to {val_path}")


if __name__ == "__main__":
    main()
